sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
branches:
  except:
    # Don't run for version tags
    - "/^v\\d+\\.\\d+\\.\\d+(\\-.*)?$/"
before_script:
  - npm prune
  - npm update
script:
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
